### PR TITLE
Update lein to 2.5.1

### PR DESCRIPTION
**Pull request by abhinavrau**
Older version of lein had problems downloading some dependencies from fusesource. Upgrading to the lein 2.5.1 fixes the issue

### CODE REVIEW

**Comment by abhinavrau** [comment]
Please review this change to upgrade to lein 2.5.1 and let me know if it's OK.

**Comment by charles-dyfis-net** [comment]
There's a lot of needless POSIX incompatibility in that script, but I assume that that's a thing I should take up with Leiningen upstream rather than with you. :)

**Comment by craigbro** [comment]
Charles Duffy <notifications@github.com> writes:

> There's a lot of needless POSIX incompatibility in that script, but I
> assume that that's a thing I should take up with Leiningen upstream
> rather than with you. :)

I think the response will be much the same 8^)


-- 
Craig Brozefsky
Lead Engineer, ThreatGRID R&D
Cisco Security Group
+1-773-469-8349

**Comment by charles-dyfis-net** [comment]
@abhinavrau, can you check whether you still need this with 6e8f800b07ba2bf20128c537b4a2f32fb31edf0e merged?

**Comment by charles-dyfis-net** [comment]
Actually -- we have other problems related to use of old lein (in particular, 2.0 doesn't support `uberjar-merge-with`, which results in generating uberjars wherein Lucene doesn't work properly).

**Pull request merged**
